[package]
name = "raynet-core"
version.workspace = true
edition.workspace = true

[features]
fastack-conserve = []

[dependencies]
aegis.workspace = true
bytes.workspace = true
fastbloom.workspace = true
log.workspace = true
num_enum.workspace = true
rand.workspace = true
thiserror.workspace = true
